### ISSUE TITLE
Navbar error

### ISSUE THREAD

**Issue by Mathildeuh** [AzuriomCommunity/Plugin-Changelog#1]
![image](https://user-images.githubusercontent.com/76065396/116310537-6a9ec100-a7aa-11eb-9ada-ab03b76749e7.png)

**Comment by GameWatch21** [comment]
Just a simple solution
Create a Navbar with External Link and add `/changelog` to the link field and done

**Comment by MrMicky-FR** [comment]
Hi, this issues was fixed in d87d49cc0574d23fe3c5fdb1aab982bec32b0213, you can update the plugin to the version `1.1.0`
