### ISSUE TITLE
Discord Webhook or Rss Feed

### ISSUE THREAD

**Issue by Doldak** [AzuriomCommunity/Plugin-Changelog#2]
a Discord Webhook or a
Rss feed are a nice idea for this changelog?

**Comment by JoeDalton9027** [comment]
I'm agree that coule be a great idea !

**Comment by xlanyleeet** [comment]
Support for webhooks has not been added?🥲

**Comment by MrMicky-FR** [comment]
As you can see not yet, but the plugin is open source, if you need this you can make a pull request or find someone who can do it
