### ISSUE TITLE
Changelog on admin panel does not show more than 15 updates

### ISSUE THREAD

**Issue by ModoSN** [AzuriomCommunity/Plugin-Changelog#3]
There is no pagination or sorting available to be able to see more than 15 updates at {url}/admin/changelog/updates

<img width="959" alt="image" src="https://user-images.githubusercontent.com/13785654/167394279-3ec40df1-d235-4a14-a17d-e36ee1cf8358.png">

You can still create updates but to edit them you have to manually navigate to {url}/admin/changelog/updates/18/edit for example.

On Azurion FiveM 1.0.2

**Comment by JamesBach93** [comment]
The Problem is still happend after 1 Year....  :/

**Comment by MrMicky-FR** [comment]
Fixed in #11
