### ISSUE TITLE
Suggest: Create groups of categories

### ISSUE THREAD

**Issue by Axtazer** [AzuriomCommunity/Plugin-Changelog#5]
Hello, I propose for the plugin can create a category group such as: 
Minecraft-Server -> Build - Quest - Ext... 
Website -> Shop - Wiki - Forum - Ext...

Not in list, but a configuration like:
![image](https://user-images.githubusercontent.com/47863741/172044250-6899f316-b682-4f6a-bc9b-423b3c51df56.png)
And have something on the site with the same idea

**Comment by MrMicky-FR** [comment]
Not planned for now due to lack of activity of the original author 😕
