### ISSUE TITLE
Suggestion: Discord Webhook Integration. 

### ISSUE THREAD

**Issue by ghost** [AzuriomCommunity/Plugin-Changelog#6]
As the title suggest, it would be cool if the plugin could POST to a webhook the contents of it's message into a nice Discord Embed for Discord Servers.

**Comment by Wakleg** [comment]
I agree I was just going to propose this feature

**Comment by JoeDalton9027** [comment]
I'm agree too !

**Comment by crashzk** [comment]
+1

duplicate #2

**Comment by MrMicky-FR** [comment]
Added in version 1.2.2 🚀
