### ISSUE TITLE
Suggestion: All Updates, allow for them to show most recent at top.

### ISSUE THREAD

**Issue by ghost** [AzuriomCommunity/Plugin-Changelog#7]
Greetings,

Currently on Changelog, under the website.com/changelog section and under the tab "All Updates", the logs post as "Oldest" first and it would be great to have it show "Newest" instead. Could this be a toggle feature?

Thank you,
0xBit

**Comment by DongShaoNB** [comment]
I agree with you, perhaps adding an option for this would be better

**Comment by MrMicky-FR** [comment]
Added in version 1.2.1
